"""First migration

Revision ID: 4c855277bcc5
Revises:
Create Date: 2024-07-04 09:37:13.471590

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4c855277bcc5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
